RMQ_HOST = localhost
RMQ_USERNAME = guest
RMQ_PASSWORD = guest
RMQ_PORT = 5672
LOCAL_RMQ_ENV = RMQ_HOST=${RMQ_HOST} RMQ_USERNAME=${RMQ_USERNAME} RMQ_PASSWORD=${RMQ_PASSWORD} RMQ_PORT=${RMQ_PORT}

run:
	export ${LOCAL_RMQ_ENV} && go run main.go
